version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:8083
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - NODE_ENV=development
      - PORT=8083
      - MONGODB_URI=mongodb://172.30.1.14:27017/farm
    volumes:
      - .:/app
      - /app/node_modules
    command: node server.js
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data: 